/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Admin.DB;
import javax.swing.JOptionPane;
/**
 *
 * @author Lovish
 */
public class ViewIssued extends javax.swing.JFrame {

    /**
     * Creates new form ViewIssued
     */
    String stuid;
    public ViewIssued(String sidd) {
        initComponents();
        stuid = sidd;
        populateTable();
    }
    
    void populateTable()
    {
        try
        {
            String cols[] = {"ID","Title","Author","Publisher","Price"};
            
            
            String qry = "select count(*)NOR from tbissue where issuestuid = '" + stuid + "'";
            DB obj = new DB();
            ResultSet rs = obj.execute(qry);
            
            int rows = rs.getInt("NOR");
           /* if(rows == null)
            {
                JOpti
            }*/
            String data[][] = new String[rows][5];
            
            qry = "select issuebookid from tbissue where issuestuid = '" + stuid + "'";
            rs = obj.execute(qry);
            
            while(rs.next())
            {
                int bid = rs.getInt("bookid");
                qry = "select * from tbbook where bookid = " + bid ;
                rs = obj.execute(qry);
                int i =0,j =0;
            
                
                data[i][j++] = rs.getString("bookid");
                data[i][j++] = rs.getString("booktit");
                data[i][j++] = rs.getString("bookaut");
                data[i][j++] = rs.getString("bookpub");
                data[i][j++] = rs.getString("bookprc");
                
                j = 0;
                i++;
            }
            
           
            /*
            rs = obj.execute("select * from tbbook");
            int i =0,j =0;
            
            while(rs.next())
            {
                data[i][j++] = rs.getString("bookid");
                data[i][j++] = rs.getString("booktit");
                data[i][j++] = rs.getString("bookaut");
                data[i][j++] = rs.getString("bookpub");
                data[i][j++] = rs.getString("bookprc");
                
                j = 0;
                i++;
            }*/
            
            DefaultTableModel dtm = new DefaultTableModel(data,cols);
            jTable1.setModel(dtm);
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"No book has been issued to you");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Issued Books");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
